### PR TITLE
Fix passing string variable to an external application.

### PR DESCRIPTION
**Pull request by aheubusch**
I was a bit hasty with my previous PR (#398).
Do you guys know of any other type that implements IEnumerable but isn't really a collection of items?

### CODE REVIEW

**Comment by ForNeVeR** [comment]
We have a test failure:
```
TestHost.FileSystemTests.ShellExecutionTest.WinFileShouldBeExecutedFromSystemPath("file.bat","123","file")
     Expected string length 3 but was 0. Strings differ at index 0.
  Expected: "123"
  But was:  <string.Empty>
```

**Comment by ForNeVeR** [comment]
I don't know context of this change (will check later), but I fear that you may now have some `StringConstant` instead of `string` after my recent changes in parameter passing (see #397). If that is the case, then please notify me, and I'll take a closer look at these changes and how we could change either my or yours code to mitigate the issue.

**Comment by aheubusch** [comment]
As far as I can tell your changes are not related to the failing test.
Locally the test executes fine. Maybe its something on the CI server?

**Comment by ForNeVeR** [comment]
Well, that's interesting. This test was written by me and I can confirm that it executes in my local environment after applying this pull request. Could someone of the project owners restart the build on AppVeyor?

cc @JayBazuzi

**Comment by JayBazuzi** [comment]
Restarted.

-J

**Comment by ForNeVeR** [comment]
Still fails. I'll add Appveyor to my personal repo and make some experiments later. We need to fix that. I think that may be related to changes in `CatchCommandResult` method but still cannot reproduce that.

**Comment by ForNeVeR** [comment]
It seems to me that it's appveyor local problem. Currently our naster branch fails at my Appveyor instance: https://ci.appveyor.com/project/ForNeVeR/pash/build/1.0.2

It means that there's something wrong with Appveyor or with our test.

**Comment by aheubusch** [comment]
My guess is we resolve `file` incorrectly in `CommandManager.ResolveAbsolutePath`. Its possible we find a `file.exe` before the intended `file.bat`.

**Comment by ForNeVeR** [comment]
Thanks for your investigation!

**Pull request merged**
